/**
 * EmoCare UI copy — Español.
 * Keep Emo / Mira identity names unchanged. Correct accents.
 */

export default {
  // —— common ——
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.done': 'Listo',
  'common.skip': 'Omitir',
  'common.continue': 'Continuar',
  'common.delete': 'Eliminar',
  'common.close': 'Cerrar',
  'common.back': 'Atrás',
  'common.retry': 'Reintentar',
  'common.ok': 'OK',
  'common.off': 'Desactivado',
  'common.on': 'Activado',
  'common.notSet': 'Sin definir',
  'common.loading': 'Cargando…',
  'common.errorGeneric': 'Algo salió un poco mal. Inténtalo de nuevo.',
  'common.couldNotSave': 'No se pudo guardar',
  'common.openSettings': 'Abrir Ajustes',
  'common.privacyPolicy': 'Política de privacidad',
  'common.terms': 'Términos de servicio',
  'common.tryAgain': 'Inténtalo de nuevo.',
  'common.view': 'Ver',
  'common.open': 'Abrir',
  'common.export': 'Exportar',
  'common.forget': 'Olvidar',
  'common.remove': 'Quitar',

  // —— nav ——
  'nav.home': 'Inicio',
  'nav.checkin': 'Check-in',
  'nav.today': 'Mi día',
  'nav.talk': 'Hablar con Emo',
  'nav.journal': 'Diario',
  'nav.mira': 'Mira',
  'nav.openMenu': 'Abrir menú',
  'nav.goBack': 'Volver',
  'nav.goForward': 'Adelante',
  'nav.askMira': 'Preguntar a Mira',
  'nav.insights': 'Perspectivas',
  'nav.memoryLedger': 'Registro de memorias',
  'nav.settings': 'Ajustes',

  // —— brand / splash ——
  'brand.appName': 'EmoCare',
  'brand.tagline': 'Intelligence with Soul.',
  'brand.sanctuaryLine': 'Tu santuario emocional',

  // —— onboarding ——
  'onboarding.welcomeEyebrow': 'BIENVENIDA A EMOCARE',
  'onboarding.welcomeTitle': 'Conoce a Emo y Mira\nen tu santuario.',
  'onboarding.welcomeBody':
    'EmoCare es un espacio privado para la conciencia emocional, la reflexión y una guía amable.',
  'onboarding.meetCompanions': 'Conoce a Emo y Mira en tu santuario.',
  'onboarding.companionsTitle': 'Tus compañeros',
  'onboarding.companionsBody':
    'Emo — un compañero cálido para emociones, check-ins y Talk.\n\nMira — orientación atenta para claridad, estrategia y perspectiva.\n\nAmbos son compañeros de IA — no profesionales humanos. Tus conversaciones están pensadas para sentirse emocionalmente seguras, privadas y bajo tu control.',
  'onboarding.welcomeQuote': 'No necesitas las palabras perfectas. Solo empieza.',
  'onboarding.privacyTitle': 'Tus pensamientos\nse quedan contigo.',
  'onboarding.privacyLead': 'Cifrados en tu dispositivo.\nNunca se venden.',
  'onboarding.ageTitle': 'EmoCare es para adultos\nde 18 años o más.',
  'onboarding.ageBody':
    'Para proteger a los usuarios más jóvenes, confirma tu edad antes de continuar. Tu respuesta se queda en este dispositivo.',
  'onboarding.ageConfirm': 'Confirmo que tengo 18 años de edad o más.',
  'onboarding.ageMustBe18': 'Debes tener 18 años o más para usar EmoCare.',
  'onboarding.aboutYouTitle': 'Cuéntame\nsobre ti.',
  'onboarding.aboutYouSub':
    'Solo lo que ayuda a Emo y Mira a acompañarte. Puedes cambiarlo en cualquier momento en Tu nombre y perfil.',
  'onboarding.preferredName': 'Nombre preferido',
  'onboarding.preferredNamePlaceholder': 'Opcional',
  'onboarding.pronouns': 'Pronombres (opcional)',
  'onboarding.pronounsPlaceholder': 'p. ej. ella, él, elle',
  'onboarding.emoLanguage': 'Idioma de Emo',
  'onboarding.miraLanguage': 'Idioma de Mira',
  'onboarding.howFeelingOptional': '¿Cómo te sientes hoy? (opcional)',
  'onboarding.continueHome': 'Continuar al inicio',
  'onboarding.skipForNow': 'Omitir por ahora',
  'onboarding.privacyAck': 'He leído esto y entiendo cómo se usa mi información.',
  'onboarding.privacyUnderstand': 'Entiendo y continuar',
  'onboarding.continueArrow': 'Continuar →',
  'onboarding.encryptedDevice': 'Cifrado en tu dispositivo',
  'onboarding.neverSold': 'Nunca se vende',
  'onboarding.aiMayProcess': 'Conversaciones con IA',
  'onboarding.privacyCardBody1':
    'Las entradas del diario y los datos del Memory Ledger permanecen en tu dispositivo: cifrados y accesibles solo para ti.',
  'onboarding.privacyCardBody2': 'Nunca vendemos tu información.',
  'onboarding.privacyCardBody3':
    'Tus mensajes de chat los procesa la IA de Anthropic para generar las respuestas de Emo. Solo se transmiten los mensajes de chat. Nada se almacena a largo plazo en nuestros servidores.',
  'onboarding.privacyClarify':
    'Las conversaciones son privadas para ti. Las memorias que guardes se pueden revisar o eliminar en cualquier momento en Memory Ledger. Emo y Mira son compañeros de IA: no terapeutas con licencia ni servicios de crisis. Si estás en peligro inmediato, contacta a los servicios de emergencia locales.',
  'onboarding.legalAgree': 'Al continuar, aceptas los {terms} y la {privacy}.',
  'onboarding.memoryLedgerControl': 'Control del Memory Ledger',
  'onboarding.memoryLedgerControlBody':
    'Consulta, gestiona y elimina tus datos de contexto y registros históricos en cualquier momento.',
  'onboarding.fullTransparency': 'Transparencia total',
  'onboarding.fullTransparencyBody': 'Creemos en la claridad, la honestidad y tu control total.',
  'onboarding.slideWelcome': 'Bienvenida',
  'onboarding.slideAge': 'Verificación de edad',
  'onboarding.slidePrivacy': 'Privacidad',
  'onboarding.slideAboutYou': 'Cuéntame sobre ti',
  'onboarding.ageEyebrow': 'ANTES DE CONTINUAR',
  'onboarding.orEnterDob': 'o introduce tu fecha de nacimiento',
  'onboarding.dateOfBirth': 'Fecha de nacimiento',
  'onboarding.dobMonth': 'MM',
  'onboarding.dobDay': 'DD',
  'onboarding.dobYear': 'AAAA',
  'onboarding.birthMonthA11y': 'Mes de nacimiento',
  'onboarding.birthDayA11y': 'Día de nacimiento',
  'onboarding.birthYearA11y': 'Año de nacimiento',
  'onboarding.validDob': 'Introduce una fecha de nacimiento válida.',
  'onboarding.ageContinueHint':
    'Confirma que tienes 18+ o introduce tu fecha de nacimiento completa para continuar.',
  'onboarding.ageBlockedTitle': 'EmoCare es para adultos 18+',
  'onboarding.ageBlockedBody':
    'Gracias por tu honestidad. EmoCare está diseñado para personas de 18 años o más, así que no podemos abrir la experiencia completa ahora.',
  'onboarding.ageBlockedSupport':
    'Mereces apoyo adecuado a tu edad. Estas líneas son gratuitas, privadas y atendidas por personas que escuchan:',
  'onboarding.tapToConnect': 'Toca para conectar',
  'onboarding.goBack': '← Volver',
  'onboarding.privacyAckA11y': 'Reconozco la información de privacidad',
  'onboarding.stepA11y': 'Ir al paso {current} de {total}',
  'onboarding.moodAckHeavy':
    'Gracias por confiarme algo pesado. Podemos sostenerlo con suavidad juntos.',
  'onboarding.moodAckOverwhelmed':
    'Cuando todo parece demasiado, una respiración a la vez es suficiente.',
  'onboarding.moodAckNeutral':
    'Neutral es honesto — hay sabiduría en simplemente presentarte.',
  'onboarding.moodAckHopeful': 'La esperanza es una luz suave. Ya la veo en ti.',
  'onboarding.moodAckLight': 'La ligereza merece celebrarse. Estoy aquí contigo en ella.',
  'onboarding.moodAckPeaceful':
    'La paz es una fuerza silenciosa. Me alegra que la hayas nombrado.',
  'onboarding.moodAckGrateful': 'La gratitud abre el corazón. Eso es hermoso.',
  'onboarding.moodAckJoyful':
    'La alegría está viva en ti — me alegra que te hayas permitido sentirla.',
  'onboarding.moodAckFallback': 'Te escucho — {mood} es válido, y no estás solo/a.',
  'onboarding.emoLabel': 'Emo',

  // —— home ——
  'home.sanctuary': 'Santuario',
  'home.talkToEmo': 'Hablar con Emo 💜',
  'home.talkBlurb': 'Lo que haya en tu corazón, podemos empezar ahí.',
  'home.startConversation': 'Empezar conversación',
  'home.mira': 'Preguntar a Mira',
  'home.miraBlurb':
    'Claridad, perspectiva y orientación atenta para las preguntas que tienes en mente.',
  'home.startExploring': 'Empezar a explorar',
  'home.todaysJourney': 'El viaje de hoy',
  'home.howFeeling': '¿Cómo te sientes hoy?',
  'home.emotionalInsights': 'Perspectivas emocionales',
  'home.emotionalInsightsBody': 'Descubre patrones y ritmos en tu viaje emocional.',
  'home.viewInsights': 'Ver perspectivas',
  'home.memoryLedger': 'Registro de memorias',
  'home.memoryLedgerBody':
    'Lo que Emo guarda en este dispositivo: contexto personal, hitos y cómo se usa la memoria.',
  'home.openLedger': 'Abrir registro',
  'home.eveningReflection': 'Reflexión nocturna',
  'home.eveningReflectionBody':
    'Al cerrar el día… ¿Qué necesita todavía un poco de cariño hoy?',
  'home.reflectJournal': 'Reflexionar en el diario',
  'home.sanctuaryFooter': 'EmoCare no es atención de emergencia.',
  'home.needHelp': '¿Necesitas ayuda inmediata?',
  'home.notificationsA11y': 'Ajustes de notificaciones',
  'home.sanctuarySub': 'Este es tu santuario. ♡',
  'home.checkIn': 'Check-in',

  // —— checkin ——
  'checkin.title': 'Tómate un momento contigo.',
  'checkin.subtitle': '¿Qué se siente más verdadero ahora mismo?',
  'checkin.save': 'Guardar check-in →',
  'checkin.notePlaceholder': 'Hoy me siento...',
  'checkin.completeTitle': 'Check-in completo',
  'checkin.completeSub': 'Te tomaste un momento para ti hoy.',
  'checkin.talkWithEmo': 'Hablar con Emo',
  'checkin.returnSanctuary': 'Volver al santuario',
  'checkin.talkHint': '¿Te gustaría hablar de esto con Emo?',
  'checkin.talkHintNamed':
    'Hiciste check-in como {mood}. ¿Te gustaría hablar de esto con Emo?',
  'checkin.intensityWhisper': 'Susurro',
  'checkin.intensitySoft': 'Suave',
  'checkin.intensityPresent': 'Presente',
  'checkin.intensityStrong': 'Fuerte',
  'checkin.intensityDeep': 'Profundo',
  'checkin.intensityTitle': '¿Qué tan fuerte es este sentimiento hoy?',
  'checkin.whatsOnHeart': '¿Qué hay en tu corazón?',
  'checkin.fewWordsEnough': 'No tienes que explicarlo todo. Unas pocas palabras bastan.',
  'checkin.chooseFeeling': 'Elige un sentimiento para guardar tu check-in.',
  'checkin.privacyNote': 'Tu check-in es privado y seguro',
  'checkin.deleteToday': 'Eliminar los check-ins de hoy',
  'checkin.deleteTodayBody': 'Se eliminarán todas las actualizaciones de ánimo registradas hoy.',
  'checkin.addingUpdate':
    'Añadiendo otro momento al viaje de hoy: tus check-ins anteriores se quedan como estaban.',
  'checkin.navTitle': 'Check-in',

  // —— today ——
  'today.title': 'Mi día',
  'today.dayAhead': 'Tu día por delante',
  'today.subtitle': 'Intenciones, no presión: planificar a tu ritmo.',
  'today.gentleNote': 'Nota amable',
  'today.intentions': 'Intenciones de hoy',
  'today.emptyIntentions':
    'Aún no hay nada en tu lista: toca una sugerencia amable abajo, o escribe la tuya.',
  'today.whatMatters': '¿Qué importa hoy?',
  'today.addIntention': 'Añadir intención',
  'today.begin': 'Empezar →',
  'today.removeIntention': '¿Quitar intención?',
  'today.removeConfirm': '¿Quitar “{title}” de hoy?',
  'today.moreIdeas': 'Más ideas',
  'today.tryOne': 'Probar una',
  'today.gentleGrowth': 'Crecimiento amable',
  'today.emoReflection': 'Reflexión de Emo',

  // —— talk ——
  'talk.startConversation': 'Empezar conversación',
  'talk.saveToJournal': 'Guardar en el diario',
  'talk.rememberThis': 'Recordar esto',
  'talk.emoWriting': 'Emo está escribiendo…',
  'talk.thinkingWithYou': 'Pensando contigo…',
  'talk.deleteConversation': 'Eliminar conversación',
  'talk.deleteConversationBody': '¿Eliminar todos los mensajes de esta conversación?',
  'talk.nothingToSave': 'Nada que guardar',
  'talk.nothingToSaveBody': 'Empieza una conversación primero.',
  'talk.permissionNeeded': 'Permiso necesario',
  'talk.permissionPhotos': 'Permite el acceso a fotos para compartir imágenes con Emo.',
  'talk.errorGentle': 'Algo salió un poco mal. Inténtalo de nuevo.',
  'talk.newChat': 'Chat nuevo',
  'talk.chatHistory': 'Historial de chats',
  'talk.inputPlaceholder': '¿Qué hay en tu corazón?',
  'talk.photoFromLibrary': 'Foto de la biblioteca',
  'talk.howFeelingNow': '¿Cómo te sientes ahora?',
  'talk.headerTagline': 'Intelligence with Soul',
  'talk.welcomeBack': 'Bienvenido de nuevo.',
  'talk.emoWithYou': 'Emo está contigo.',
  'talk.whatsOnHeartToday': '¿Qué hay en tu corazón hoy?',
  'talk.helloNamed': 'Hola, {name} 💜',

  // —— journal ——
  'journal.title': 'Tu diario',
  'journal.helperCopy':
    'Empieza donde te resulte más fácil.\nUn pensamiento, un sentimiento, un momento—\nno hay una sola forma correcta de empezar.',
  'journal.placeholder': 'Escribe aquí lo que llevas en el corazón…',
  'journal.saveReflection': 'Guardar reflexión',
  'journal.reflectWithEmo': 'Reflexionar con Emo',
  'journal.recent': 'Recientes',
  'journal.empty': 'Tus reflexiones se reunirán aquí a medida que escribas.',
  'journal.deleteTitle': '¿Eliminar esta reflexión?',
  'journal.deleteBody': 'Esto no se puede deshacer.',
  'journal.yourJourney': 'Tu viaje',
  'journal.savedHint': 'Guardado en tu diario',
  'journal.writeFirst': 'Escribe primero y luego guarda',

  // —— mira ——
  'mira.controls': 'Controles de Mira',
  'mira.researchDeeper': 'Investigar más a fondo',
  'mira.seeSources': 'Ver fuentes',
  'mira.clearChat': 'Borrar conversación',
  'mira.clearConfirm': '¿Borrar esta conversación con Mira?',
  'mira.availableAfterReply': 'Disponible después de que Mira responda',
  'mira.sendA11y': 'Enviar a Mira',
  'mira.thinking': 'Investigando…',
  'mira.thinkingLong': 'Buscando fuentes fiables y sintetizando…',
  'mira.drawnFromSources': 'Basado en {count} fuentes publicadas',
  'mira.drawnFromOne': 'Basado en una fuente publicada',
  'mira.saveResponse': 'Guardar respuesta',
  'mira.inputPlaceholder': '¿Qué te gustaría explorar con Mira?',
  'mira.emptyRole': 'Pídele a Mira que investigue, analice o te guíe…',
  'mira.tagline': 'Investigación • Estrategia • Perspectiva sabia',
  'mira.nothingToSaveBody': 'Hazle primero una pregunta a Mira.',
  'mira.clear': 'Borrar',
  'mira.nothingToSave': 'Nada que guardar',
  'mira.savedTitle': 'Guardado',
  'mira.savedBody': 'Esta respuesta de Mira se guardó en tu biblioteca.',
  'mira.stayHere': 'Quedarme aquí',
  'mira.viewInsights': 'Ver Insights',
  'mira.sources': 'Fuentes',
  'mira.noSources': 'No se adjuntaron fuentes publicadas a esta respuesta.',
  'mira.publishedSources': 'Fuentes publicadas',
  'mira.selectModeA11y': 'Seleccionar estilo de respuesta de Mira',
  'mira.currentModeHint': 'Modo actual {mode}',
  'mira.availableAfterSources': 'Disponible tras una investigación con fuentes',
  'mira.privacyFooter': 'Privado para ti · Mira piensa con cuidado',
  'mira.thinkingQuick': 'Mira está pensando…',
  'mira.thinkingWise': 'Reuniendo conocimiento y perspectiva…',
  'mira.languageA11y': 'Idioma de Mira, {language}',

  // —— insights ——
  'insights.title': 'Perspectivas',
  'insights.landscape': 'Tu paisaje emocional',
  'insights.landscapeSub': 'Reflexión, no informe: comprender a tu ritmo.',
  'insights.gentleInsight': 'Perspectiva amable',
  'insights.weather': 'Clima emocional',
  'insights.weatherEmpty':
    'Haz check-in cuando estés listo: tus estados de ánimo se reunirán aquí como un clima suave.',
  'insights.weatherEmptyLive':
    'Tus cielos emocionales tomarán forma a medida que hagas check-in esta semana.',
  'insights.whatHelped': 'Lo que ayudó esta semana',
  'insights.whatHelpedEmpty':
    'Paseos, diario, respiración, tiempo con Emo: registra lo que te levantó esta semana.',
  'insights.log': 'Registrar',
  'insights.gentleGrowth': 'Crecimiento amable',
  'insights.emoReflection': 'Reflexión de Emo',

  // —— memory ——
  'memory.title': 'Registro de memorias',
  'memory.subtitle': 'Un registro de momentos que ayudaron a dar forma a tu viaje.',
  'memory.emoRemembers': 'Emo recuerda',
  'memory.featured': 'Memoria destacada',
  'memory.whatRemembers': 'Lo que Emo recuerda',
  'memory.empty':
    'Tu línea de tiempo crecerá a medida que hagas check-in, escribas en el diario y hables con Emo.',
  'memory.emptyCategory':
    'Aún no hay memorias en esta categoría: tu historia sigue desplegándose.',
  'memory.forgetTitle': '¿Olvidar esta memoria?',
  'memory.forgetBody': 'Emo dejará de mostrar “{label}” en este dispositivo.',
  'memory.privacyNote': 'Guardado solo en este dispositivo. Nada se comparte. Nada se vende.',
  'memory.yourJourney': 'Tu viaje',
  'memory.reflection': 'Reflexión de la memoria',

  // —— settings ——
  'settings.title': 'Ajustes',
  'settings.account': 'CUENTA',
  'settings.app': 'APP',
  'settings.privacy': 'PRIVACIDAD',
  'settings.safety': 'SEGURIDAD Y APOYO',
  'settings.about': 'ACERCA DE',
  'settings.name': 'Nombre',
  'settings.pronouns': 'Pronombres',
  'settings.timezone': 'Zona horaria',
  'settings.emoLanguage': 'Idioma de Emo',
  'settings.appPasscode': 'Código de la app',
  'settings.appPasscodeHint': 'Bloquea EmoCare cuando salgas de la app.',
  'settings.changePasscode': 'Cambiar código',
  'settings.useBiometrics': 'Usar biometría',
  'settings.useBiometricsHint': 'Desbloquea con {label} después de configurar el código.',
  'settings.memoryLedger': 'Registro de memorias',
  'settings.exportData': 'Exportar mis datos',
  'settings.helpSupport': 'Ayuda y soporte',
  'settings.viewIntro': 'Ver la introducción de nuevo',
  'settings.appVersion': 'Versión de la app',
  'settings.deleteAll': 'Eliminar todos los datos',
  'settings.deleteAllTitle': '¿Eliminar todos los datos?',
  'settings.deleteAllBody':
    'Esto elimina de forma permanente tus check-ins, entradas del diario, memorias, historial de chat, perspectivas de Mira y datos de la app de este dispositivo. Tu nombre y los ajustes de la app se quedan.',
  'settings.deleteAllConfirm': 'Eliminar todos los datos',
  'settings.dataDeletedTitle': 'Datos eliminados',
  'settings.dataDeletedBody': 'Tu santuario se ha restablecido. La bienvenida empieza de nuevo.',
  'settings.resetOnboarding': 'Restablecer onboarding (Dev)',
  'settings.resetOnboardingTitle': '¿Restablecer onboarding?',
  'settings.resetOnboardingBody':
    'La bienvenida aparecerá de nuevo en el próximo inicio. El chat y el diario se quedan a menos que elimines todos los datos.',
  'settings.installApp': 'Instalar la app EmoCare',
  'settings.installShort': 'Instalar',
  'settings.howToShort': 'Cómo',
  'settings.installed': 'Instalada',
  'settings.installHowTo': 'Cómo instalar EmoCare',
  'settings.installHint':
    'Añade EmoCare al dock o a la pantalla de inicio para un santuario con sensación nativa.',
  'settings.installedHint': 'EmoCare está en tu dock o pantalla de inicio.',
  'settings.crisisTitle': 'Si necesitas ayuda ahora',
  'settings.crisisBody':
    'Si estás en crisis o puedes hacerte daño, contacta de inmediato a los servicios de emergencia locales o a una línea de crisis.',
  'settings.callCrisis': 'Llamar a la línea de crisis',
  'settings.textCrisis': 'Enviar SMS a la línea de crisis',
  'settings.crisisCompanion': 'EmoCare es una app compañera: Emo no es atención de emergencia.',
  'settings.disclaimer':
    'EmoCare es para la reflexión emocional y el crecimiento personal. No es atención médica, terapia, diagnóstico, tratamiento ni apoyo en crisis. Destinado a usuarios de 18 años o más.',
  'settings.dailyReminders': 'Recordatorios diarios',
  'settings.emoLanguageHint':
    'Elige el idioma que Emo usa al hablar contigo. Automático sigue el idioma de tu mensaje. Mira tiene un ajuste de idioma aparte.',

  // —— profile ——
  'profile.title': 'Tu nombre y perfil',
  'profile.namePlaceholder': 'Nombre preferido',
  'profile.pronounsPlaceholder': 'p. ej. ella, él, elle',

  // —— passcode ——
  'passcode.enter': 'Introduce el código',
  'passcode.create': 'Crear un código',
  'passcode.confirm': 'Confirmar código',
  'passcode.change': 'Elegir código nuevo',
  'passcode.incorrect': 'Código incorrecto.',
  'passcode.incorrectRetry': 'Código incorrecto. Inténtalo de nuevo.',
  'passcode.unlockBiometric': 'Desbloquear con {label}',
  'passcode.digitA11y': 'Dígito {digit}',
  'passcode.deleteA11y': 'Borrar',
  'passcode.subtitle': 'Tus conversaciones y tu diario se quedan privados en este dispositivo.',
  'passcode.createHint': 'Usa 4 dígitos para bloquear EmoCare cuando salgas de la app.',
  'passcode.confirmHint': 'Introduce los mismos 4 dígitos otra vez.',
  'passcode.mismatch': 'Los códigos no coinciden.',
  'passcode.verifyCurrent': 'Introduce el código actual',
  'passcode.disableHint': 'Introduce tu código para desactivarlo.',
  'passcode.changeVerifyHint': 'Verifica primero tu código actual.',
  'passcode.sheetHint': 'Se guarda de forma segura en este dispositivo. EmoCare se bloquea cuando sales de la app.',
  'passcode.unlocking': 'Abriendo {label}…',

  // —— consent ——
  'consent.title': 'Antes de hablar con Emo',
  'consent.body':
    'Tus mensajes los procesa la IA de Anthropic para generar las respuestas de Emo. Solo se transmiten tus mensajes de chat: nada más. Los mensajes no se almacenan a largo plazo en nuestros servidores. Tu diario, check-ins y Memory Ledger se quedan solo en tu dispositivo.',
  'consent.continue': 'Entiendo — empezar a hablar',
  'consent.privacyLink': 'Ver política de privacidad',

  // —— language sheets ——
  'talkLang.title': 'Idioma de Emo',
  'talkLang.hint': 'Elige cómo te habla Emo. Guardado para Talk (separado de Mira).',
  'miraLang.title': 'Idioma de respuesta',
  'miraLang.hint':
    'Elige cómo responde Mira. Guardado por separado de Talk con Emo. El marcador de entrada sigue este idioma.',

  // —— moods ——
  'mood.peaceful': 'En paz',
  'mood.light': 'Ligero',
  'mood.heavy': 'Pesado',
  'mood.anxious': 'Ansioso',
  'mood.overwhelmed': 'Abrumado',
  'mood.grateful': 'Agradecido',
  'mood.hopeful': 'Esperanzado',
  'mood.joyful': 'Alegre',
  'mood.neutral': 'Neutral',

  // —— alerts ——
  'alert.remove': 'Quitar',
  'alert.confirmDelete': 'Confirmar eliminación',
  'alert.cancel': 'Cancelar',
  'checkin.optionalParen': "(Opcional)",
  'checkin.moodAloneEnough': "Puedes omitirlo — con el estado de ánimo basta.",
  'journal.carryThoughtOptional': "Un pensamiento que quieras llevar hoy. Opcional — se guarda en el diario.",
  'common.beginSoftly': "Puedes empezar con suavidad...",
  'settings.dailyRemindersA11y': "Recordatorios diarios, {status}",
};
