/**
 * EmoCare UI copy — Português (Brasil).
 * Emo treated as feminine (a Emo) to match existing product copy.
 * Keep Emo / Mira identity names unchanged.
 */

export default {
  // —— common ——
  'common.cancel': 'Cancelar',
  'common.save': 'Salvar',
  'common.done': 'Concluído',
  'common.skip': 'Pular',
  'common.continue': 'Continuar',
  'common.delete': 'Excluir',
  'common.close': 'Fechar',
  'common.back': 'Voltar',
  'common.retry': 'Tentar de novo',
  'common.ok': 'OK',
  'common.off': 'Desligado',
  'common.on': 'Ligado',
  'common.notSet': 'Não definido',
  'common.loading': 'Carregando…',
  'common.errorGeneric': 'Algo deu errado com delicadeza. Tente novamente.',
  'common.couldNotSave': 'Não foi possível salvar',
  'common.openSettings': 'Abrir Ajustes',
  'common.privacyPolicy': 'Política de Privacidade',
  'common.terms': 'Termos de Serviço',
  'common.tryAgain': 'Tente novamente.',
  'common.view': 'Ver',
  'common.open': 'Abrir',
  'common.export': 'Exportar',
  'common.forget': 'Esquecer',
  'common.remove': 'Remover',

  // —— nav ——
  'nav.home': 'Início',
  'nav.checkin': 'Check-in',
  'nav.today': 'Meu dia',
  'nav.talk': 'Conversar com a Emo',
  'nav.journal': 'Diário',
  'nav.mira': 'Mira',
  'nav.openMenu': 'Abrir menu',
  'nav.goBack': 'Voltar',
  'nav.goForward': 'Avançar',
  'nav.askMira': 'Perguntar à Mira',
  'nav.insights': 'Insights',
  'nav.memoryLedger': 'Registro de memórias',
  'nav.settings': 'Configurações',

  // —— brand / splash ——
  'brand.appName': 'EmoCare',
  'brand.tagline': 'Intelligence with Soul.',
  'brand.sanctuaryLine': 'Seu Santuário Emocional',

  // —— onboarding ——
  'onboarding.welcomeEyebrow': 'BEM-VINDO AO EMOCARE',
  'onboarding.welcomeTitle': 'Conheça a Emo e a Mira\nno seu santuário.',
  'onboarding.welcomeBody':
    'O EmoCare é um espaço privado para consciência emocional, reflexão e orientação gentil.',
  'onboarding.meetCompanions': 'Conheça a Emo e a Mira no seu santuário.',
  'onboarding.companionsTitle': 'Suas companheiras',
  'onboarding.companionsBody':
    'Emo — uma companheira acolhedora para sentimentos, check-ins e Talk.\n\nMira — orientação atenta para clareza, estratégia e perspectiva.\n\nAmbas são companheiras de IA — não profissionais humanas. Suas conversas são pensadas para serem emocionalmente seguras, privadas e sob o seu controle.',
  'onboarding.welcomeQuote': 'Você não precisa ter as palavras certas. É só começar.',
  'onboarding.privacyTitle': 'Seus pensamentos\nficam com você.',
  'onboarding.privacyLead': 'Criptografados no seu dispositivo.\nNunca vendidos.',
  'onboarding.ageTitle': 'O EmoCare é para adultos\nde 18 anos ou mais.',
  'onboarding.ageBody':
    'Para proteger usuários mais jovens, confirme sua idade antes de continuar. Sua resposta fica neste dispositivo.',
  'onboarding.ageConfirm': 'Confirmo que tenho 18 anos de idade ou mais.',
  'onboarding.ageMustBe18': 'É preciso ter 18 anos ou mais para usar o EmoCare.',
  'onboarding.aboutYouTitle': 'Conte-me\nsobre você.',
  'onboarding.aboutYouSub':
    'Apenas o que ajuda a Emo e a Mira a apoiar você. Você pode mudar isso a qualquer momento em Seu nome e perfil.',
  'onboarding.preferredName': 'Nome preferido',
  'onboarding.preferredNamePlaceholder': 'Opcional',
  'onboarding.pronouns': 'Pronomes (opcional)',
  'onboarding.pronounsPlaceholder': 'ex.: ela/dela, ele/dele, elu/delu',
  'onboarding.emoLanguage': 'Idioma da Emo',
  'onboarding.miraLanguage': 'Idioma da Mira',
  'onboarding.howFeelingOptional': 'Como você está se sentindo hoje? (opcional)',
  'onboarding.continueHome': 'Continuar para o Início',
  'onboarding.skipForNow': 'Pular por agora',
  'onboarding.privacyAck': 'Li isto e entendo como minhas informações são usadas.',
  'onboarding.privacyUnderstand': 'Entendi e Continuar',
  'onboarding.continueArrow': 'Continuar →',
  'onboarding.encryptedDevice': 'Criptografado no seu dispositivo',
  'onboarding.neverSold': 'Nunca vendido',
  'onboarding.aiMayProcess': 'Conversas com IA',
  'onboarding.privacyCardBody1':
    'Entradas do diário e dados do Memory Ledger ficam no seu dispositivo — criptografados e acessíveis só por você.',
  'onboarding.privacyCardBody2': 'Nunca vendemos suas informações.',
  'onboarding.privacyCardBody3':
    'Suas mensagens de chat são processadas pela IA da Anthropic para gerar as respostas da Emo. Só as mensagens de chat são transmitidas. Nada fica armazenado a longo prazo nos nossos servidores.',
  'onboarding.privacyClarify':
    'As conversas são privadas para você. Memórias que você salva podem ser revisadas ou removidas a qualquer momento no Memory Ledger. Emo e Mira são companheiras de IA — não terapeutas licenciadas nem serviços de crise. Se você estiver em perigo imediato, contate os serviços de emergência locais.',
  'onboarding.legalAgree': 'Ao continuar, você concorda com os {terms} e a {privacy}.',
  'onboarding.memoryLedgerControl': 'Controle do Memory Ledger',
  'onboarding.memoryLedgerControlBody':
    'Veja, gerencie e exclua seus dados de contexto e registros históricos a qualquer momento.',
  'onboarding.fullTransparency': 'Transparência total',
  'onboarding.fullTransparencyBody': 'Acreditamos em clareza, honestidade e no seu controle total.',
  'onboarding.slideWelcome': 'Boas-vindas',
  'onboarding.slideAge': 'Verificação de idade',
  'onboarding.slidePrivacy': 'Privacidade',
  'onboarding.slideAboutYou': 'Conte-me sobre você',
  'onboarding.ageEyebrow': 'ANTES DE CONTINUAR',
  'onboarding.orEnterDob': 'ou informe sua data de nascimento',
  'onboarding.dateOfBirth': 'Data de nascimento',
  'onboarding.dobMonth': 'MM',
  'onboarding.dobDay': 'DD',
  'onboarding.dobYear': 'AAAA',
  'onboarding.birthMonthA11y': 'Mês de nascimento',
  'onboarding.birthDayA11y': 'Dia de nascimento',
  'onboarding.birthYearA11y': 'Ano de nascimento',
  'onboarding.validDob': 'Informe uma data de nascimento válida.',
  'onboarding.ageContinueHint':
    'Confirme que você tem 18+ ou informe sua data de nascimento completa para continuar.',
  'onboarding.ageBlockedTitle': 'O EmoCare é para adultos 18+',
  'onboarding.ageBlockedBody':
    'Obrigado pela honestidade. O EmoCare foi feito para pessoas de 18 anos ou mais, então não podemos abrir a experiência completa agora.',
  'onboarding.ageBlockedSupport':
    'Você merece apoio adequado à sua idade. Estas linhas são gratuitas, privadas e atendidas por pessoas que escutam:',
  'onboarding.tapToConnect': 'Toque para conectar',
  'onboarding.goBack': '← Voltar',
  'onboarding.privacyAckA11y': 'Reconheço as informações de privacidade',
  'onboarding.stepA11y': 'Ir para a etapa {current} de {total}',
  'onboarding.moodAckHeavy':
    'Obrigado por confiar algo pesado a mim. Podemos segurar isso com cuidado juntos.',
  'onboarding.moodAckOverwhelmed':
    'Quando tudo parece demais, uma respiração de cada vez já basta.',
  'onboarding.moodAckNeutral':
    'Neutro é honesto — há sabedoria em simplesmente aparecer.',
  'onboarding.moodAckHopeful': 'A esperança é uma luz suave. Já a vejo em você.',
  'onboarding.moodAckLight': 'A leveza merece ser celebrada. Estou aqui com você nela.',
  'onboarding.moodAckPeaceful':
    'A paz é uma força quieta. Fico feliz que você a tenha nomeado.',
  'onboarding.moodAckGrateful': 'A gratidão abre o coração. Isso é bonito.',
  'onboarding.moodAckJoyful':
    'A alegria está viva em você — fico feliz que você se permitiu senti-la.',
  'onboarding.moodAckFallback': 'Eu te ouço — {mood} é válido, e você não está sozinho(a).',
  'onboarding.emoLabel': 'Emo',

  // —— home ——
  'home.sanctuary': 'Santuário',
  'home.talkToEmo': 'Conversar com a Emo 💜',
  'home.talkBlurb': 'O que estiver no seu coração, podemos começar por aí.',
  'home.startConversation': 'Iniciar conversa',
  'home.mira': 'Perguntar à Mira',
  'home.miraBlurb':
    'Clareza, perspectiva e orientação atenta para as perguntas na sua mente.',
  'home.startExploring': 'Começar a explorar',
  'home.todaysJourney': 'Jornada de hoje',
  'home.howFeeling': 'Como você está se sentindo hoje?',
  'home.emotionalInsights': 'Insights emocionais',
  'home.emotionalInsightsBody': 'Descubra padrões e ritmos na sua jornada emocional.',
  'home.viewInsights': 'Ver insights',
  'home.memoryLedger': 'Registro de memórias',
  'home.memoryLedgerBody':
    'O que a Emo guarda neste dispositivo — contexto pessoal, marcos e como a memória é usada.',
  'home.openLedger': 'Abrir registro',
  'home.eveningReflection': 'Reflexão noturna',
  'home.eveningReflectionBody':
    'Conforme o dia se encerra… O que ainda precisa de um pouco de carinho hoje?',
  'home.reflectJournal': 'Refletir no diário',
  'home.sanctuaryFooter': 'O EmoCare não é atendimento de emergência.',
  'home.needHelp': 'Precisa de ajuda imediata?',
  'home.notificationsA11y': 'Configurações de notificação',
  'home.sanctuarySub': 'Este é o seu santuário. ♡',
  'home.checkIn': 'Check-in',

  // —— checkin ——
  'checkin.title': 'Reserve um momento consigo.',
  'checkin.subtitle': 'O que parece mais verdadeiro agora?',
  'checkin.save': 'Salvar check-in →',
  'checkin.notePlaceholder': 'Hoje eu me sinto...',
  'checkin.completeTitle': 'Check-in concluído',
  'checkin.completeSub': 'Você reservou um momento para si hoje.',
  'checkin.talkWithEmo': 'Conversar com a Emo',
  'checkin.returnSanctuary': 'Voltar ao Santuário',
  'checkin.talkHint': 'Gostaria de falar sobre isso com a Emo?',
  'checkin.talkHintNamed':
    'Você fez check-in como {mood}. Gostaria de falar sobre isso com a Emo?',
  'checkin.intensityWhisper': 'Sussurro',
  'checkin.intensitySoft': 'Suave',
  'checkin.intensityPresent': 'Presente',
  'checkin.intensityStrong': 'Forte',
  'checkin.intensityDeep': 'Profundo',
  'checkin.intensityTitle': 'Quão forte está esse sentimento hoje?',
  'checkin.whatsOnHeart': 'O que está no seu coração?',
  'checkin.fewWordsEnough': 'Você não precisa explicar tudo. Poucas palavras bastam.',
  'checkin.chooseFeeling': 'Escolha um sentimento para salvar seu check-in.',
  'checkin.privacyNote': 'Seu check-in é privado e seguro',
  'checkin.deleteToday': 'Excluir check-ins de hoje',
  'checkin.deleteTodayBody': 'Todas as atualizações de humor registradas hoje serão removidas.',
  'checkin.addingUpdate':
    'Adicionando outro momento à jornada de hoje — seus check-ins anteriores permanecem como estavam.',
  'checkin.navTitle': 'Check-in',

  // —— today ——
  'today.title': 'Meu dia',
  'today.dayAhead': 'Seu dia à frente',
  'today.subtitle': 'Intenções, não pressão — planejando no seu ritmo.',
  'today.gentleNote': 'Nota gentil',
  'today.intentions': 'Intenções de hoje',
  'today.emptyIntentions':
    'Nada na lista ainda — toque numa sugestão gentil abaixo, ou escreva a sua.',
  'today.whatMatters': 'O que importa hoje?',
  'today.addIntention': 'Adicionar intenção',
  'today.begin': 'Começar →',
  'today.removeIntention': 'Remover intenção?',
  'today.removeConfirm': 'Remover “{title}” de hoje?',
  'today.moreIdeas': 'Mais ideias',
  'today.tryOne': 'Experimentar uma',
  'today.gentleGrowth': 'Crescimento gentil',
  'today.emoReflection': 'Reflexão da Emo',

  // —— talk ——
  'talk.startConversation': 'Iniciar conversa',
  'talk.saveToJournal': 'Salvar no diário',
  'talk.rememberThis': 'Lembrar disso',
  'talk.emoWriting': 'A Emo está escrevendo…',
  'talk.thinkingWithYou': 'Pensando com você…',
  'talk.deleteConversation': 'Excluir conversa',
  'talk.deleteConversationBody': 'Remover todas as mensagens desta conversa?',
  'talk.nothingToSave': 'Nada para salvar',
  'talk.nothingToSaveBody': 'Comece uma conversa primeiro.',
  'talk.permissionNeeded': 'Permissão necessária',
  'talk.permissionPhotos': 'Permita o acesso às fotos para compartilhar imagens com a Emo.',
  'talk.errorGentle': 'Algo deu errado com delicadeza. Tente novamente.',
  'talk.newChat': 'Nova conversa',
  'talk.chatHistory': 'Histórico de conversas',
  'talk.inputPlaceholder': 'O que está no seu coração?',
  'talk.photoFromLibrary': 'Foto da biblioteca',
  'talk.howFeelingNow': 'Como você está se sentindo agora?',
  'talk.headerTagline': 'Intelligence with Soul',
  'talk.welcomeBack': 'Bem-vindo de volta.',
  'talk.emoWithYou': 'A Emo está com você.',
  'talk.whatsOnHeartToday': 'O que está no seu coração hoje?',
  'talk.helloNamed': 'Olá, {name} 💜',

  // —— journal ——
  'journal.title': 'Seu diário',
  'journal.helperCopy':
    'Comece onde for mais fácil.\nUm pensamento, um sentimento, um momento—\nnão há um único jeito certo de começar.',
  'journal.placeholder': 'Escreva aqui o que está no seu coração…',
  'journal.saveReflection': 'Salvar reflexão',
  'journal.reflectWithEmo': 'Refletir com a Emo',
  'journal.recent': 'Recentes',
  'journal.empty': 'Suas reflexões se reunirão aqui conforme você escrever.',
  'journal.deleteTitle': 'Excluir esta reflexão?',
  'journal.deleteBody': 'Isso não pode ser desfeito.',
  'journal.yourJourney': 'Sua jornada',
  'journal.savedHint': 'Salvo no seu diário',
  'journal.writeFirst': 'Escreva primeiro, depois salve',

  // —— mira ——
  'mira.controls': 'Controles da Mira',
  'mira.researchDeeper': 'Pesquisar mais a fundo',
  'mira.seeSources': 'Ver fontes',
  'mira.clearChat': 'Limpar conversa',
  'mira.clearConfirm': 'Limpar esta conversa com a Mira?',
  'mira.availableAfterReply': 'Disponível depois que a Mira responder',
  'mira.sendA11y': 'Enviar para a Mira',
  'mira.thinking': 'Pesquisando…',
  'mira.thinkingLong': 'Buscando fontes confiáveis e sintetizando…',
  'mira.drawnFromSources': 'Com base em {count} fontes publicadas',
  'mira.drawnFromOne': 'Com base em uma fonte publicada',
  'mira.saveResponse': 'Salvar resposta',
  'mira.inputPlaceholder': 'O que você gostaria que a Mira explorasse?',
  'mira.emptyRole': 'Peça à Mira para pesquisar, analisar ou orientar você…',
  'mira.tagline': 'Pesquisa • Estratégia • Perspectiva sábia',
  'mira.nothingToSaveBody': 'Faça uma pergunta à Mira primeiro.',
  'mira.clear': 'Limpar',
  'mira.nothingToSave': 'Nada para salvar',
  'mira.savedTitle': 'Salvo',
  'mira.savedBody': 'Esta resposta da Mira foi salva na sua biblioteca.',
  'mira.stayHere': 'Ficar aqui',
  'mira.viewInsights': 'Ver Insights',
  'mira.sources': 'Fontes',
  'mira.noSources': 'Nenhuma fonte publicada foi anexada a esta resposta.',
  'mira.publishedSources': 'Fontes publicadas',
  'mira.selectModeA11y': 'Selecionar estilo de resposta da Mira',
  'mira.currentModeHint': 'Modo atual {mode}',
  'mira.availableAfterSources': 'Disponível após pesquisa com fontes',
  'mira.privacyFooter': 'Privado para você · A Mira pensa com cuidado',
  'mira.thinkingQuick': 'A Mira está pensando…',
  'mira.thinkingWise': 'Reunindo conhecimento e perspectiva…',
  'mira.languageA11y': 'Idioma da Mira, {language}',

  // —— insights ——
  'insights.title': 'Insights',
  'insights.landscape': 'Sua paisagem emocional',
  'insights.landscapeSub': 'Reflexão, não relatório — compreensão no seu ritmo.',
  'insights.gentleInsight': 'Insight gentil',
  'insights.weather': 'Clima emocional',
  'insights.weatherEmpty':
    'Faça check-in quando estiver pronto — seus humores se reunirão aqui como um clima suave.',
  'insights.weatherEmptyLive':
    'Seus céus emocionais vão tomar forma conforme você fizer check-in esta semana.',
  'insights.whatHelped': 'O que ajudou esta semana',
  'insights.whatHelpedEmpty':
    'Caminhadas, diário, respiração, tempo com a Emo — registre o que te ergueu esta semana.',
  'insights.log': 'Registrar',
  'insights.gentleGrowth': 'Crescimento gentil',
  'insights.emoReflection': 'Reflexão da Emo',

  // —— memory ——
  'memory.title': 'Registro de memórias',
  'memory.subtitle': 'Um registro de momentos que ajudaram a moldar sua jornada.',
  'memory.emoRemembers': 'A Emo lembra',
  'memory.featured': 'Memória em destaque',
  'memory.whatRemembers': 'O que a Emo lembra',
  'memory.empty':
    'Sua linha do tempo crescerá conforme você fizer check-in, escrever no diário e conversar com a Emo.',
  'memory.emptyCategory': 'Ainda não há memórias nesta categoria — sua história ainda está se desenrolando.',
  'memory.forgetTitle': 'Esquecer esta memória?',
  'memory.forgetBody': 'A Emo deixará de trazer “{label}” neste dispositivo.',
  'memory.privacyNote': 'Armazenado só neste dispositivo. Nada compartilhado. Nada vendido.',
  'memory.yourJourney': 'Sua jornada',
  'memory.reflection': 'Reflexão da memória',

  // —— settings ——
  'settings.title': 'Configurações',
  'settings.account': 'CONTA',
  'settings.app': 'APP',
  'settings.privacy': 'PRIVACIDADE',
  'settings.safety': 'SEGURANÇA E APOIO',
  'settings.about': 'SOBRE',
  'settings.name': 'Nome',
  'settings.pronouns': 'Pronomes',
  'settings.timezone': 'Fuso horário',
  'settings.emoLanguage': 'Idioma da Emo',
  'settings.appPasscode': 'Senha do app',
  'settings.appPasscodeHint': 'Bloqueie o EmoCare quando sair do app.',
  'settings.changePasscode': 'Alterar senha',
  'settings.useBiometrics': 'Usar biometria',
  'settings.useBiometricsHint': 'Desbloqueie com {label} depois de definir a senha.',
  'settings.memoryLedger': 'Registro de memórias',
  'settings.exportData': 'Exportar meus dados',
  'settings.helpSupport': 'Ajuda e suporte',
  'settings.viewIntro': 'Ver introdução de novo',
  'settings.appVersion': 'Versão do app',
  'settings.deleteAll': 'Excluir todos os dados',
  'settings.deleteAllTitle': 'Excluir todos os dados?',
  'settings.deleteAllBody':
    'Isso remove permanentemente check-ins, entradas do diário, memórias, histórico de chat, insights da Mira e dados do app deste dispositivo. Seu nome e configurações do app permanecem.',
  'settings.deleteAllConfirm': 'Excluir todos os dados',
  'settings.dataDeletedTitle': 'Dados excluídos',
  'settings.dataDeletedBody': 'Seu santuário foi reiniciado. A boas-vindas começa de novo.',
  'settings.resetOnboarding': 'Redefinir onboarding (Dev)',
  'settings.resetOnboardingTitle': 'Redefinir onboarding?',
  'settings.resetOnboardingBody':
    'A boas-vindas aparecerá de novo no próximo lançamento. Chat e diário permanecem, a menos que você exclua todos os dados.',
  'settings.installApp': 'Instalar o app EmoCare',
  'settings.installShort': 'Instalar',
  'settings.howToShort': 'Como',
  'settings.installed': 'Instalado',
  'settings.installHowTo': 'Como instalar o EmoCare',
  'settings.installHint':
    'Adicione o EmoCare à dock ou à tela inicial para um santuário com cara nativa.',
  'settings.installedHint': 'O EmoCare está na sua dock ou tela inicial.',
  'settings.crisisTitle': 'Se você precisa de ajuda agora',
  'settings.crisisBody':
    'Se você está em crise ou pode se machucar, contate imediatamente os serviços de emergência locais ou uma linha de crise.',
  'settings.callCrisis': 'Ligar para a linha de crise',
  'settings.textCrisis': 'Enviar SMS para a linha de crise',
  'settings.crisisCompanion': 'O EmoCare é um app companheiro — a Emo não é atendimento de emergência.',
  'settings.disclaimer':
    'O EmoCare é para reflexão emocional e crescimento pessoal. Não é atendimento médico, terapia, diagnóstico, tratamento ou apoio em crise. Destinado a usuários com 18 anos ou mais.',
  'settings.dailyReminders': 'Lembretes diários',
  'settings.emoLanguageHint':
    'Escolha o idioma que a Emo usa para falar com você. A opção Automático acompanha o idioma da sua mensagem. A Mira possui uma configuração de idioma separada.',

  // —— profile ——
  'profile.title': 'Seu nome e perfil',
  'profile.namePlaceholder': 'Nome preferido',
  'profile.pronounsPlaceholder': 'ex.: ela/dela, ele/dele, elu/delu',

  // —— passcode ——
  'passcode.enter': 'Digite a senha',
  'passcode.create': 'Criar uma senha',
  'passcode.confirm': 'Confirmar senha',
  'passcode.change': 'Escolher nova senha',
  'passcode.incorrect': 'Senha incorreta.',
  'passcode.incorrectRetry': 'Senha incorreta. Tente novamente.',
  'passcode.unlockBiometric': 'Desbloquear com {label}',
  'passcode.digitA11y': 'Dígito {digit}',
  'passcode.deleteA11y': 'Apagar',
  'passcode.subtitle': 'Suas conversas e diário permanecem privados neste dispositivo.',
  'passcode.createHint': 'Use 4 dígitos para bloquear o EmoCare quando sair do app.',
  'passcode.confirmHint': 'Digite os mesmos 4 dígitos novamente.',
  'passcode.mismatch': 'As senhas não coincidem.',
  'passcode.verifyCurrent': 'Digite a senha atual',
  'passcode.disableHint': 'Digite sua senha para desativá-la.',
  'passcode.changeVerifyHint': 'Verifique primeiro sua senha atual.',
  'passcode.sheetHint': 'Armazenada com segurança neste dispositivo. O EmoCare trava quando você sai do app.',
  'passcode.unlocking': 'Abrindo {label}…',

  // —— consent ——
  'consent.title': 'Antes de conversar com a Emo',
  'consent.body':
    'Suas mensagens são processadas pela IA da Anthropic para gerar as respostas da Emo. Só suas mensagens de chat são transmitidas — nada mais. As mensagens não ficam armazenadas a longo prazo nos nossos servidores. Seu diário, check-ins e Memory Ledger ficam só no seu dispositivo.',
  'consent.continue': 'Entendi — começar a conversar',
  'consent.privacyLink': 'Ver Política de Privacidade',

  // —— language sheets ——
  'talkLang.title': 'Idioma da Emo',
  'talkLang.hint': 'Escolha como a Emo fala com você. Salvo para Conversar (separado da Mira).',
  'miraLang.title': 'Idioma de resposta',
  'miraLang.hint':
    'Escolha como a Mira responde. Salvo separadamente do Talk da Emo. O placeholder da entrada acompanha este idioma.',

  // —— moods ——
  'mood.peaceful': 'Em paz',
  'mood.light': 'Leve',
  'mood.heavy': 'Pesado',
  'mood.anxious': 'Ansioso',
  'mood.overwhelmed': 'Sobrecarregado',
  'mood.grateful': 'Grato',
  'mood.hopeful': 'Esperançoso',
  'mood.joyful': 'Alegre',
  'mood.neutral': 'Neutro',

  // —— alerts ——
  'alert.remove': 'Remover',
  'alert.confirmDelete': 'Confirmar exclusão',
  'alert.cancel': 'Cancelar',
  'checkin.optionalParen': "(Opcional)",
  'checkin.moodAloneEnough': "Pode pular — só o humor já basta.",
  'journal.carryThoughtOptional': "Um pensamento que você gostaria de levar hoje. Opcional — salvo no diário.",
  'common.beginSoftly': "Você pode começar com suavidade...",
  'settings.dailyRemindersA11y': "Lembretes diários, {status}",
};
