/**
 * EmoCare UI copy — Bahasa Indonesia.
 * Keep Emo / Mira identity names unchanged.
 */

export default {
  // —— common ——
  'common.cancel': 'Batal',
  'common.save': 'Simpan',
  'common.done': 'Selesai',
  'common.skip': 'Lewati',
  'common.continue': 'Lanjut',
  'common.delete': 'Hapus',
  'common.close': 'Tutup',
  'common.back': 'Kembali',
  'common.retry': 'Coba lagi',
  'common.ok': 'OK',
  'common.off': 'Mati',
  'common.on': 'Aktif',
  'common.notSet': 'Belum diatur',
  'common.loading': 'Memuat…',
  'common.errorGeneric': 'Ada yang kurang beres. Silakan coba lagi.',
  'common.couldNotSave': 'Tidak dapat menyimpan',
  'common.openSettings': 'Buka Pengaturan',
  'common.privacyPolicy': 'Kebijakan Privasi',
  'common.terms': 'Ketentuan Layanan',
  'common.tryAgain': 'Silakan coba lagi.',
  'common.view': 'Lihat',
  'common.open': 'Buka',
  'common.export': 'Ekspor',
  'common.forget': 'Lupakan',
  'common.remove': 'Hapus',

  // —— nav ——
  'nav.home': 'Beranda',
  'nav.checkin': 'Check-in',
  'nav.today': 'Hariku',
  'nav.talk': 'Ngobrol dengan Emo',
  'nav.journal': 'Jurnal',
  'nav.mira': 'Mira',
  'nav.openMenu': 'Buka menu',
  'nav.goBack': 'Kembali',
  'nav.goForward': 'Maju',
  'nav.askMira': 'Tanya Mira',
  'nav.insights': 'Wawasan',
  'nav.memoryLedger': 'Catatan memori',
  'nav.settings': 'Pengaturan',

  // —— brand / splash ——
  'brand.appName': 'EmoCare',
  'brand.tagline': 'Intelligence with Soul.',
  'brand.sanctuaryLine': 'Suaka Emosional Anda',

  // —— onboarding ——
  'onboarding.welcomeEyebrow': 'SELAMAT DATANG DI EMOCARE',
  'onboarding.welcomeTitle': 'Temui Emo & Mira\ndi suaka Anda.',
  'onboarding.welcomeBody':
    'EmoCare adalah ruang pribadi untuk kesadaran emosional, refleksi, dan panduan yang lembut.',
  'onboarding.meetCompanions': 'Temui Emo & Mira di suaka Anda.',
  'onboarding.companionsTitle': 'Teman Anda',
  'onboarding.companionsBody':
    'Emo — teman hangat untuk perasaan, check-in, dan Talk.\n\nMira — panduan yang penuh pertimbangan untuk kejelasan, strategi, dan perspektif.\n\nKeduanya adalah teman AI — bukan profesional manusia. Percakapan Anda dirancang agar terasa aman secara emosional, pribadi, dan dalam kendali Anda.',
  'onboarding.welcomeQuote': 'Anda tidak perlu punya kata yang tepat. Cukup mulai.',
  'onboarding.privacyTitle': 'Pikiran Anda\ntetap milik Anda.',
  'onboarding.privacyLead': 'Terenkripsi di perangkat Anda.\nTidak pernah dijual.',
  'onboarding.ageTitle': 'EmoCare untuk dewasa\n18 tahun ke atas.',
  'onboarding.ageBody':
    'Untuk melindungi pengguna yang lebih muda, mohon konfirmasi usia Anda sebelum melanjutkan. Jawaban Anda tetap di perangkat ini.',
  'onboarding.ageConfirm': 'Saya menegaskan bahwa saya berusia 18 tahun atau lebih.',
  'onboarding.ageMustBe18': 'Anda harus berusia 18 tahun atau lebih untuk memakai EmoCare.',
  'onboarding.aboutYouTitle': 'Ceritakan\ntentang diri Anda.',
  'onboarding.aboutYouSub':
    'Hanya yang membantu Emo dan Mira mendukung Anda. Anda bisa mengubahnya kapan saja di Nama & Profil Anda.',
  'onboarding.preferredName': 'Nama panggilan',
  'onboarding.preferredNamePlaceholder': 'Opsional',
  'onboarding.pronouns': 'Pronomina (opsional)',
  'onboarding.pronounsPlaceholder': 'mis. she/her, he/him, they/them',
  'onboarding.emoLanguage': 'Bahasa Emo',
  'onboarding.miraLanguage': 'Bahasa Mira',
  'onboarding.howFeelingOptional': 'Bagaimana perasaan Anda hari ini? (opsional)',
  'onboarding.continueHome': 'Lanjut ke Beranda',
  'onboarding.skipForNow': 'Lewati dulu',
  'onboarding.privacyAck': 'Saya telah membaca ini dan memahami bagaimana informasi saya digunakan.',
  'onboarding.privacyUnderstand': 'Saya Mengerti dan Lanjut',
  'onboarding.continueArrow': 'Lanjut →',
  'onboarding.encryptedDevice': 'Terenkripsi di perangkat Anda',
  'onboarding.neverSold': 'Tidak pernah dijual',
  'onboarding.aiMayProcess': 'Percakapan AI',
  'onboarding.privacyCardBody1':
    'Entri jurnal dan data Memory Ledger tetap di perangkat Anda — terenkripsi dan hanya dapat diakses oleh Anda.',
  'onboarding.privacyCardBody2': 'Kami tidak pernah menjual informasi Anda.',
  'onboarding.privacyCardBody3':
    'Pesan obrolan Anda diproses oleh AI Anthropic untuk membuat balasan Emo. Hanya pesan obrolan yang dikirim. Tidak ada yang disimpan jangka panjang di server kami.',
  'onboarding.privacyClarify':
    'Percakapan bersifat pribadi untuk Anda. Memori yang Anda simpan dapat ditinjau atau dihapus kapan saja di Memory Ledger. Emo dan Mira adalah teman AI — bukan terapis berlisensi atau layanan krisis. Jika Anda dalam bahaya segera, hubungi layanan darurat setempat.',
  'onboarding.legalAgree': 'Dengan melanjutkan, Anda menyetujui {terms} dan {privacy}.',
  'onboarding.memoryLedgerControl': 'Kontrol Memory Ledger',
  'onboarding.memoryLedgerControlBody':
    'Lihat, kelola, dan hapus data konteks serta log ledger historis kapan saja.',
  'onboarding.fullTransparency': 'Transparansi penuh',
  'onboarding.fullTransparencyBody': 'Kami percaya pada kejelasan, kejujuran, dan kendali penuh Anda.',
  'onboarding.slideWelcome': 'Selamat datang',
  'onboarding.slideAge': 'Verifikasi usia',
  'onboarding.slidePrivacy': 'Privasi',
  'onboarding.slideAboutYou': 'Ceritakan tentang Anda',
  'onboarding.ageEyebrow': 'SEBELUM MELANJUTKAN',
  'onboarding.orEnterDob': 'atau masukkan tanggal lahir Anda',
  'onboarding.dateOfBirth': 'Tanggal lahir',
  'onboarding.dobMonth': 'BB',
  'onboarding.dobDay': 'TT',
  'onboarding.dobYear': 'TTTT',
  'onboarding.birthMonthA11y': 'Bulan lahir',
  'onboarding.birthDayA11y': 'Tanggal lahir',
  'onboarding.birthYearA11y': 'Tahun lahir',
  'onboarding.validDob': 'Masukkan tanggal lahir yang valid.',
  'onboarding.ageContinueHint':
    'Konfirmasi Anda berusia 18+ atau masukkan tanggal lahir lengkap untuk melanjutkan.',
  'onboarding.ageBlockedTitle': 'EmoCare untuk dewasa 18+',
  'onboarding.ageBlockedBody':
    'Terima kasih atas kejujuran Anda. EmoCare dirancang untuk usia 18 tahun ke atas, jadi kami belum bisa membuka pengalaman lengkap sekarang.',
  'onboarding.ageBlockedSupport':
    'Anda pantas mendapat dukungan yang sesuai usia. Saluran ini gratis, pribadi, dan dijalankan oleh orang yang siap mendengar:',
  'onboarding.tapToConnect': 'Ketuk untuk terhubung',
  'onboarding.goBack': '← Kembali',
  'onboarding.privacyAckA11y': 'Saya mengakui informasi privasi',
  'onboarding.stepA11y': 'Ke langkah {current} dari {total}',
  'onboarding.moodAckHeavy':
    'Terima kasih sudah mempercayakan sesuatu yang berat. Kita bisa menahannya dengan lembut bersama.',
  'onboarding.moodAckOverwhelmed':
    'Saat semuanya terasa terlalu banyak, satu napas demi satu napas sudah cukup.',
  'onboarding.moodAckNeutral':
    'Netral itu jujur — ada kebijaksanaan hanya dengan hadir.',
  'onboarding.moodAckHopeful': 'Harapan adalah cahaya lembut. Saya sudah melihatnya di diri Anda.',
  'onboarding.moodAckLight':
    'Rasa ringan layak dirayakan. Saya di sini bersama Anda di dalamnya.',
  'onboarding.moodAckPeaceful':
    'Damai adalah kekuatan yang tenang. Saya senang Anda menamainya.',
  'onboarding.moodAckGrateful': 'Rasa syukur membuka hati. Itu indah.',
  'onboarding.moodAckJoyful':
    'Kegembiraan hidup di dalam Anda — saya senang Anda membiarkan diri merasakannya.',
  'onboarding.moodAckFallback':
    'Saya mendengar Anda — {mood} valid, dan Anda tidak sendirian.',
  'onboarding.emoLabel': 'Emo',

  // —— home ——
  'home.sanctuary': 'Suaka',
  'home.talkToEmo': 'Ngobrol dengan Emo 💜',
  'home.talkBlurb': 'Apa pun yang ada di hati Anda, kita bisa mulai dari situ.',
  'home.startConversation': 'Mulai Percakapan',
  'home.mira': 'Tanya Mira',
  'home.miraBlurb':
    'Kejelasan, perspektif, dan panduan yang penuh pertimbangan untuk pertanyaan di pikiran Anda.',
  'home.startExploring': 'Mulai Menjelajah',
  'home.todaysJourney': 'Perjalanan Hari Ini',
  'home.howFeeling': 'Bagaimana perasaan Anda hari ini?',
  'home.emotionalInsights': 'Wawasan Emosional',
  'home.emotionalInsightsBody': 'Temukan pola dan ritme dalam perjalanan emosional Anda.',
  'home.viewInsights': 'Lihat Wawasan',
  'home.memoryLedger': 'Catatan Memori',
  'home.memoryLedgerBody':
    'Yang diingat Emo di perangkat ini — konteks pribadi, tonggak, dan cara memori digunakan.',
  'home.openLedger': 'Buka Catatan',
  'home.eveningReflection': 'Refleksi Sore',
  'home.eveningReflectionBody':
    'Saat hari hampir berakhir… Apa yang masih butuh sedikit kebaikan hari ini?',
  'home.reflectJournal': 'Refleksi di Jurnal',
  'home.sanctuaryFooter': 'EmoCare bukan perawatan darurat.',
  'home.needHelp': 'Butuh bantuan segera?',
  'home.notificationsA11y': 'Pengaturan notifikasi',
  'home.sanctuarySub': 'Ini adalah ruang tenaramu. ♡',
  'home.checkIn': 'Check-in',

  // —— checkin ——
  'checkin.title': 'Luangkan waktu sejenak untuk diri sendiri.',
  'checkin.subtitle': 'Apa yang paling terasa benar saat ini?',
  'checkin.save': 'Simpan Check-In →',
  'checkin.notePlaceholder': 'Hari ini saya merasa...',
  'checkin.completeTitle': 'Check-In Selesai',
  'checkin.completeSub': 'Anda meluangkan waktu untuk diri sendiri hari ini.',
  'checkin.talkWithEmo': 'Ngobrol dengan Emo',
  'checkin.returnSanctuary': 'Kembali ke Suaka',
  'checkin.talkHint': 'Mau membicarakan ini dengan Emo?',
  'checkin.talkHintNamed':
    'Anda check-in sebagai {mood}. Mau membicarakan ini dengan Emo?',
  'checkin.intensityWhisper': 'Bisikan',
  'checkin.intensitySoft': 'Lembut',
  'checkin.intensityPresent': 'Hadir',
  'checkin.intensityStrong': 'Kuat',
  'checkin.intensityDeep': 'Dalam',
  'checkin.intensityTitle': 'Seberapa kuat perasaan ini hari ini?',
  'checkin.whatsOnHeart': 'Apa yang ada di hati Anda?',
  'checkin.fewWordsEnough': 'Anda tidak perlu menjelaskan semuanya. Beberapa kata sudah cukup.',
  'checkin.chooseFeeling': 'Pilih perasaan untuk menyimpan check-in Anda.',
  'checkin.privacyNote': 'Check-in Anda bersifat pribadi dan aman',
  'checkin.deleteToday': 'Hapus check-in hari ini',
  'checkin.deleteTodayBody': 'Semua pembaruan suasana hati yang dicatat hari ini akan dihapus.',
  'checkin.addingUpdate':
    'Menambahkan momen lain ke perjalanan hari ini — check-in sebelumnya tetap seperti semula.',
  'checkin.navTitle': 'Check In',

  // —— today ——
  'today.title': 'Hariku',
  'today.dayAhead': 'Hari di depan Anda',
  'today.subtitle': 'Niat, bukan tekanan — merencanakan dengan tempo Anda.',
  'today.gentleNote': 'Catatan Lembut',
  'today.intentions': 'Niat Hari Ini',
  'today.emptyIntentions':
    'Belum ada di daftar — ketuk saran lembut di bawah, atau tulis sendiri.',
  'today.whatMatters': 'Apa yang penting hari ini?',
  'today.addIntention': 'Tambah Niat',
  'today.begin': 'Mulai →',
  'today.removeIntention': 'Hapus niat?',
  'today.removeConfirm': 'Hapus “{title}” dari hari ini?',
  'today.moreIdeas': 'Ide lainnya',
  'today.tryOne': 'Coba satu',
  'today.gentleGrowth': 'Pertumbuhan Lembut',
  'today.emoReflection': 'Refleksi Emo',

  // —— talk ——
  'talk.startConversation': 'Mulai Percakapan',
  'talk.saveToJournal': 'Simpan ke jurnal',
  'talk.rememberThis': 'Ingat ini',
  'talk.emoWriting': 'Emo sedang menulis…',
  'talk.thinkingWithYou': 'Berpikir bersama Anda…',
  'talk.deleteConversation': 'Hapus percakapan',
  'talk.deleteConversationBody': 'Hapus semua pesan dalam percakapan ini?',
  'talk.nothingToSave': 'Tidak ada yang disimpan',
  'talk.nothingToSaveBody': 'Mulai percakapan dulu.',
  'talk.permissionNeeded': 'Izin diperlukan',
  'talk.permissionPhotos': 'Izinkan akses foto untuk berbagi gambar dengan Emo.',
  'talk.errorGentle': 'Ada yang kurang beres. Silakan coba lagi.',
  'talk.newChat': 'Obrolan baru',
  'talk.chatHistory': 'Riwayat obrolan',
  'talk.inputPlaceholder': 'Apa yang ada di hati Anda?',
  'talk.photoFromLibrary': 'Foto dari perpustakaan',
  'talk.howFeelingNow': 'Bagaimana perasaan Anda sekarang?',
  'talk.headerTagline': 'Intelligence with Soul',
  'talk.welcomeBack': 'Selamat datang kembali.',
  'talk.emoWithYou': 'Emo ada bersama Anda.',
  'talk.whatsOnHeartToday': 'Apa yang ada di hati Anda hari ini?',
  'talk.helloNamed': 'Halo, {name} 💜',

  // —— journal ——
  'journal.title': 'Jurnal Anda',
  'journal.helperCopy':
    'Mulai dari mana pun yang terasa paling mudah.\nSebuah pikiran, sebuah perasaan, sebuah momen—\ntidak ada satu cara yang benar untuk memulai.',
  'journal.placeholder': 'Tulis apa yang ada di hatimu di sini…',
  'journal.saveReflection': 'Simpan refleksi',
  'journal.reflectWithEmo': 'Refleksi dengan Emo',
  'journal.recent': 'Terbaru',
  'journal.empty': 'Refleksi Anda akan berkumpul di sini saat Anda menulis.',
  'journal.deleteTitle': 'Hapus refleksi ini?',
  'journal.deleteBody': 'Ini tidak dapat dibatalkan.',
  'journal.yourJourney': 'Perjalanan Anda',
  'journal.savedHint': 'Disimpan ke jurnal Anda',
  'journal.writeFirst': 'Tulis dulu, lalu simpan',

  // —— mira ——
  'mira.controls': 'Kontrol Mira',
  'mira.researchDeeper': 'Riset lebih dalam',
  'mira.seeSources': 'Lihat sumber',
  'mira.clearChat': 'Hapus percakapan',
  'mira.clearConfirm': 'Hapus percakapan Mira ini?',
  'mira.availableAfterReply': 'Tersedia setelah Mira membalas',
  'mira.sendA11y': 'Kirim ke Mira',
  'mira.thinking': 'Meneliti…',
  'mira.thinkingLong': 'Mencari sumber terpercaya dan mensintesis…',
  'mira.drawnFromSources': 'Diambil dari {count} sumber terbitan',
  'mira.drawnFromOne': 'Diambil dari satu sumber terbitan',
  'mira.saveResponse': 'Simpan respons',
  'mira.inputPlaceholder': 'Apa yang ingin Anda jelajahi bersama Mira?',
  'mira.emptyRole': 'Minta Mira meneliti, menganalisis, atau membimbing Anda…',
  'mira.tagline': 'Riset • Strategi • Perspektif Bijak',
  'mira.nothingToSaveBody': 'Tanya Mira dulu.',
  'mira.clear': 'Hapus',
  'mira.nothingToSave': 'Tidak ada yang disimpan',
  'mira.savedTitle': 'Disimpan',
  'mira.savedBody': 'Jawaban Mira ini disimpan ke perpustakaan Anda.',
  'mira.stayHere': 'Tetap di sini',
  'mira.viewInsights': 'Lihat Insights',
  'mira.sources': 'Sumber',
  'mira.noSources': 'Tidak ada sumber terbitan yang dilampirkan pada balasan ini.',
  'mira.publishedSources': 'Sumber terbitan',
  'mira.selectModeA11y': 'Pilih gaya respons Mira',
  'mira.currentModeHint': 'Mode saat ini {mode}',
  'mira.availableAfterSources': 'Tersedia setelah riset ber-sumber',
  'mira.privacyFooter': 'Privat untuk Anda · Mira berpikir dengan cermat',
  'mira.thinkingQuick': 'Mira sedang berpikir…',
  'mira.thinkingWise': 'Mengumpulkan pengetahuan dan perspektif…',
  'mira.languageA11y': 'Bahasa Mira, {language}',

  // —— insights ——
  'insights.title': 'Wawasan',
  'insights.landscape': 'Lanskap emosional Anda',
  'insights.landscapeSub': 'Refleksi, bukan laporan — memahami dengan tempo Anda.',
  'insights.gentleInsight': 'Wawasan Lembut',
  'insights.weather': 'Cuaca Emosional',
  'insights.weatherEmpty':
    'Check-in saat Anda siap — suasana hati Anda akan berkumpul di sini seperti cuaca lembut.',
  'insights.weatherEmptyLive':
    'Langit emosional Anda akan terbentuk saat Anda check-in minggu ini.',
  'insights.whatHelped': 'Yang Membantu Minggu Ini',
  'insights.whatHelpedEmpty':
    'Jalan kaki, jurnal, napas, waktu dengan Emo — catat apa yang mengangkat Anda minggu ini.',
  'insights.log': 'Catat',
  'insights.gentleGrowth': 'Pertumbuhan Lembut',
  'insights.emoReflection': 'Refleksi Emo',

  // —— memory ——
  'memory.title': 'Catatan Memori',
  'memory.subtitle': 'Catatan momen yang membantu membentuk perjalanan Anda.',
  'memory.emoRemembers': 'Emo mengingat',
  'memory.featured': 'Memori Unggulan',
  'memory.whatRemembers': 'Yang Diingat Emo',
  'memory.empty': 'Linimasa Anda akan tumbuh saat Anda check-in, menulis jurnal, dan ngobrol dengan Emo.',
  'memory.emptyCategory': 'Belum ada memori di kategori ini — cerita Anda masih berlangsung.',
  'memory.forgetTitle': 'Lupakan memori ini?',
  'memory.forgetBody': 'Emo akan berhenti menampilkan “{label}” di perangkat ini.',
  'memory.privacyNote': 'Hanya disimpan di perangkat ini. Tidak dibagikan. Tidak dijual.',
  'memory.yourJourney': 'Perjalanan Anda',
  'memory.reflection': 'Refleksi Memori',

  // —— settings ——
  'settings.title': 'Pengaturan',
  'settings.account': 'AKUN',
  'settings.app': 'APLIKASI',
  'settings.privacy': 'PRIVASI',
  'settings.safety': 'KESELAMATAN & DUKUNGAN',
  'settings.about': 'TENTANG',
  'settings.name': 'Nama',
  'settings.pronouns': 'Pronomina',
  'settings.timezone': 'Zona waktu',
  'settings.emoLanguage': 'Bahasa Emo',
  'settings.appPasscode': 'Kode sandi aplikasi',
  'settings.appPasscodeHint': 'Kunci EmoCare saat Anda meninggalkan aplikasi.',
  'settings.changePasscode': 'Ubah kode sandi',
  'settings.useBiometrics': 'Gunakan biometrik',
  'settings.useBiometricsHint': 'Buka dengan {label} setelah kode sandi diatur.',
  'settings.memoryLedger': 'Catatan Memori',
  'settings.exportData': 'Ekspor data saya',
  'settings.helpSupport': 'Bantuan & Dukungan',
  'settings.viewIntro': 'Lihat Pengenalan Lagi',
  'settings.appVersion': 'Versi aplikasi',
  'settings.deleteAll': 'Hapus semua data',
  'settings.deleteAllTitle': 'Hapus semua data?',
  'settings.deleteAllBody':
    'Ini menghapus secara permanen check-in, entri jurnal, memori, riwayat obrolan, wawasan Mira, dan data aplikasi dari perangkat ini. Nama dan pengaturan aplikasi tetap.',
  'settings.deleteAllConfirm': 'Hapus Semua Data',
  'settings.dataDeletedTitle': 'Data dihapus',
  'settings.dataDeletedBody': 'Suaka Anda telah diatur ulang. Selamat datang dimulai lagi.',
  'settings.resetOnboarding': 'Reset Onboarding (Dev)',
  'settings.resetOnboardingTitle': 'Reset onboarding?',
  'settings.resetOnboardingBody':
    'Welcome akan muncul lagi saat peluncuran berikutnya. Obrolan dan jurnal tetap kecuali Anda menghapus semua data.',
  'settings.installApp': 'Pasang aplikasi EmoCare',
  'settings.installShort': 'Pasang',
  'settings.howToShort': 'Cara',
  'settings.installed': 'Terpasang',
  'settings.installHowTo': 'Cara memasang EmoCare',
  'settings.installHint':
    'Tambahkan EmoCare ke dock atau layar beranda untuk suaka yang terasa lebih native.',
  'settings.installedHint': 'EmoCare ada di dock atau layar beranda Anda.',
  'settings.crisisTitle': 'Jika Anda butuh bantuan sekarang',
  'settings.crisisBody':
    'Jika Anda dalam krisis atau mungkin menyakiti diri sendiri, segera hubungi layanan darurat setempat atau hotline krisis.',
  'settings.callCrisis': 'Telepon jalur krisis',
  'settings.textCrisis': 'SMS jalur krisis',
  'settings.crisisCompanion': 'EmoCare adalah aplikasi teman — Emo bukan perawatan darurat.',
  'settings.disclaimer':
    'EmoCare untuk refleksi emosional dan pertumbuhan pribadi. Bukan perawatan medis, terapi, diagnosis, pengobatan, atau dukungan krisis. Ditujukan untuk pengguna berusia 18 tahun ke atas.',
  'settings.dailyReminders': 'Pengingat harian',
  'settings.emoLanguageHint':
    'Pilih bahasa yang digunakan Emo saat berbicara denganmu. Otomatis akan mengikuti bahasa pesanmu. Mira memiliki pengaturan bahasa tersendiri.',

  // —— profile ——
  'profile.title': 'Nama & profil Anda',
  'profile.namePlaceholder': 'Nama panggilan',
  'profile.pronounsPlaceholder': 'mis. she/her, he/him, they/them',

  // —— passcode ——
  'passcode.enter': 'Masukkan kode sandi',
  'passcode.create': 'Buat kode sandi',
  'passcode.confirm': 'Konfirmasi kode sandi',
  'passcode.change': 'Pilih kode sandi baru',
  'passcode.incorrect': 'Kode sandi salah.',
  'passcode.incorrectRetry': 'Kode sandi salah. Coba lagi.',
  'passcode.unlockBiometric': 'Buka dengan {label}',
  'passcode.digitA11y': 'Digit {digit}',
  'passcode.deleteA11y': 'Hapus',
  'passcode.subtitle': 'Percakapan dan jurnal Anda tetap pribadi di perangkat ini.',
  'passcode.createHint': 'Gunakan 4 digit untuk mengunci EmoCare saat Anda meninggalkan aplikasi.',
  'passcode.confirmHint': 'Masukkan 4 digit yang sama lagi.',
  'passcode.mismatch': 'Kode sandi tidak cocok.',
  'passcode.verifyCurrent': 'Masukkan kode sandi saat ini',
  'passcode.disableHint': 'Masukkan kode sandi untuk mematikannya.',
  'passcode.changeVerifyHint': 'Verifikasi kode sandi Anda saat ini dulu.',
  'passcode.sheetHint': 'Disimpan dengan aman di perangkat ini. EmoCare terkunci saat Anda meninggalkan aplikasi.',
  'passcode.unlocking': 'Membuka {label}…',

  // —— consent ——
  'consent.title': 'Sebelum Ngobrol dengan Emo',
  'consent.body':
    'Pesan Anda diproses oleh AI Anthropic untuk membuat balasan Emo. Hanya pesan obrolan yang dikirim — tidak ada yang lain. Pesan tidak disimpan jangka panjang di server kami. Jurnal, check-in, dan Memory Ledger Anda tetap hanya di perangkat Anda.',
  'consent.continue': 'Saya Mengerti — Mulai Ngobrol',
  'consent.privacyLink': 'Lihat Kebijakan Privasi',

  // —— language sheets ——
  'talkLang.title': 'Bahasa Emo',
  'talkLang.hint': 'Pilih bagaimana Emo berbicara denganmu. Disimpan untuk Talk (terpisah dari Mira).',
  'miraLang.title': 'Bahasa respons',
  'miraLang.hint':
    'Pilih bagaimana Mira membalas. Disimpan terpisah dari Emo Talk. Placeholder input mengikuti bahasa ini.',

  // —— moods ——
  'mood.peaceful': 'Damai',
  'mood.light': 'Ringan',
  'mood.heavy': 'Berat',
  'mood.anxious': 'Cemas',
  'mood.overwhelmed': 'Kewalahan',
  'mood.grateful': 'Bersyukur',
  'mood.hopeful': 'Penuh harapan',
  'mood.joyful': 'Gembira',
  'mood.neutral': 'Netral',

  // —— alerts ——
  'alert.remove': 'Hapus',
  'alert.confirmDelete': 'Konfirmasi hapus',
  'alert.cancel': 'Batal',
  'checkin.optionalParen': "(Opsional)",
  'checkin.moodAloneEnough': "Boleh dilewati — suasana hati saja sudah cukup.",
  'journal.carryThoughtOptional': "Pikiran yang ingin kamu bawa hari ini. Opsional — disimpan di jurnal.",
  'common.beginSoftly': "Kamu bisa mulai dengan lembut...",
  'settings.dailyRemindersA11y': "Pengingat harian, {status}",
};
